export {default as Home} from "./Home.jsx"
export {default as Contact} from "./Contact.jsx"
export {default as About} from "./About.jsx"
export {default as ErrorPage} from "./ErrorPage.jsx"
export {default as Resources} from "./Resources.jsx"
export {default as Services} from "./Services.jsx"
export { default as TestListing } from "./TestListing.jsx"
export {default as Login} from "./Login.jsx"
export {default as Logout} from "./Logout.jsx"
export {default as UserProfile} from "./UserProfile.jsx"
export { default as Register } from "./Register.jsx"
export {default as ForgotPassword} from "./ForgotPassword.jsx"