export {default as Banner} from "./Banner.jsx"
export {default as CoreValues} from "./CoreValues.jsx"
export {default as CTA} from "./CTA.jsx"
export {default as Ctaii} from "./Ctaii.jsx"
export {default as FAQs} from "./FAQs.jsx"
export {default as Footer} from "./Footer.jsx"
export {default as Hero} from "./Hero.jsx"
export {default as Navbar} from "./Navbar.jsx"
export {default as Notes_Videos} from "./Notes_Videos.jsx"
export {default as Onboarding} from "./Onboarding.jsx"
export {default as OurGoal} from "./OurGoal.jsx"
export {default as OurStory} from "./OurStory.jsx"
export {default as Partners} from "./Partners.jsx"
export {default as ProductList} from "./ProductList.jsx"
export {default as Stories} from "./Stories.jsx"
export { default as Hero_About } from "./Hero_About.jsx"
export { default as Service } from "./Service.jsx"
export { default as Hero_Services } from "./Hero_Services.jsx"
export { default as Hero_Resources } from "./Hero_Resources.jsx"
export { default as ContactForm } from "./ContactForm.jsx"
export { default as Products } from "./productsComponents/Products.jsx"
export { default as ProductSidebar } from "./productsComponents/ProductSidebar.jsx"
export { default as ProductDetail } from "./productsComponents/ProductDetail.jsx"
export { default as ProductDetailParameters } from "./productsComponents/ProductDetailParameters.jsx"